name: ci

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: initc3/gramine

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build & push docker image for gramine
        uses: docker/build-push-action@v4
        with:
          context: .
          file: sgx.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
					build-args: branch=${{ GITHUB_BASE_REF }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB_BASE_REF }},
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=initc3/gramine:buildcache
          cache-to: type=registry,ref=initc3/gramine:buildcache,mode=max
