name: ci

on:
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  just_build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: initc3/gramine

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: docker/build-push-action@v4
        with:
          context: .
          file: sgx.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
					build-args: branch=${{ GITHUB_BASE_REF }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ GITHUB_BASE_REF }},
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }},
